// GENERATED FILE — do not edit by hand.
// Zoe website page inventory snapshot for the SEO matcher. Regenerate with:
//   npx tsx scripts/seo/build-zoe-pages.mts [path-to-website-repo]
// Source: <website-repo>/seo-migration-data.md (live zoeeventsdmv.com crawl). FACTS ONLY — real pages only.
//
// Generated: 2026-10-01T02:51:22.677Z
// Source file: seo-migration-data.md
// Page count: 37

import type { ZoePage } from "./types";

export const ZOE_PAGES_GENERATED_AT = "2026-10-01T02:51:22.678Z";
export const ZOE_PAGES_SOURCE = "seo-migration-data.md (zoeeventsdmv.com crawl)";

export const ZOE_PAGES: ZoePage[] = [
  {
    "path": "/",
    "url": "https://zoeeventsdmv.com",
    "title": "Zoe Events & Party Rental | Luxury Event Rentals -- DC, MD, VA",
    "h1": "Luxury Event Rentals in Loop",
    "headings": [
      "Luxury Event Rentals in Loop",
      "Our Offerings",
      "Featured Inventory",
      "Want to see more? Visit Our Inventory Page!",
      "About Us",
      "Join Our Team",
      "Follow us @ZoeeventsDMV",
      "How to Start the Rental Process?",
      "1. Create Your Wishlist",
      "2. Review Your Quote",
      "3. Reserve Your Items",
      "Get in touch"
    ],
    "category": null,
    "topic": "home",
    "intent": "commercial",
    "location": "DMV",
    "excerpt": "Zoe Events and Party Rentals offers luxury event rentals for weddings, corporate events, and social gatherings in Washington DC, Maryland, and Virginia.",
    "kind": "home"
  },
  {
    "path": "/about",
    "url": "https://zoeeventsdmv.com/about",
    "title": "About | Explore Our Services",
    "h1": null,
    "headings": [
      "Zoe Event Rentals",
      "Contact Us by Phone (301) 291-5296"
    ],
    "category": null,
    "topic": "about",
    "intent": "navigational",
    "location": "DMV",
    "excerpt": "Premium event rental company serving Rockville, MD and surrounding areas. Tables, chairs, decor, audio/video, lighting, bars, bounce houses, staging, dance floors for weddings, corporate, and social events.",
    "kind": "info"
  },
  {
    "path": "/arches",
    "url": "https://zoeeventsdmv.com/arches",
    "title": "Decor Rentals | Zoe Events & Party Rental",
    "h1": null,
    "headings": [],
    "category": "decor",
    "topic": "arches",
    "intent": "transactional",
    "location": "DMV",
    "excerpt": "Decor rental inventory from Zoe Events, serving DC, Maryland and Virginia.",
    "kind": "category"
  },
  {
    "path": "/audio-equipment-rentals",
    "url": "https://zoeeventsdmv.com/audio-equipment-rentals",
    "title": "Audio Rentals | Zoe Events & Party Rental",
    "h1": null,
    "headings": [],
    "category": "audio",
    "topic": "audio equipment rentals",
    "intent": "transactional",
    "location": "DMV",
    "excerpt": "Audio rental inventory from Zoe Events, serving DC, Maryland and Virginia.",
    "kind": "category"
  },
  {
    "path": "/audio-visual-equipment-rentals",
    "url": "https://zoeeventsdmv.com/audio-visual-equipment-rentals",
    "title": "Av Rentals | Zoe Events & Party Rental",
    "h1": null,
    "headings": [],
    "category": "av",
    "topic": "audio visual equipment rentals",
    "intent": "transactional",
    "location": "DMV",
    "excerpt": "Av rental inventory from Zoe Events, serving DC, Maryland and Virginia.",
    "kind": "category"
  },
  {
    "path": "/backdrop",
    "url": "https://zoeeventsdmv.com/backdrop",
    "title": "Decor Rentals | Zoe Events & Party Rental",
    "h1": null,
    "headings": [],
    "category": "decor",
    "topic": "backdrop",
    "intent": "transactional",
    "location": "DMV",
    "excerpt": "Decor rental inventory from Zoe Events, serving DC, Maryland and Virginia.",
    "kind": "category"
  },
  {
    "path": "/bars",
    "url": "https://zoeeventsdmv.com/bars",
    "title": "Bars Rentals | Zoe Events & Party Rental",
    "h1": null,
    "headings": [],
    "category": "bars",
    "topic": "bars",
    "intent": "transactional",
    "location": "DMV",
    "excerpt": "Bars rental inventory from Zoe Events, serving DC, Maryland and Virginia.",
    "kind": "category"
  },
  {
    "path": "/barstool",
    "url": "https://zoeeventsdmv.com/barstool",
    "title": "Seating Rentals | Zoe Events & Party Rental",
    "h1": null,
    "headings": [],
    "category": "seating",
    "topic": "barstool",
    "intent": "transactional",
    "location": "DMV",
    "excerpt": "Seating rental inventory from Zoe Events, serving DC, Maryland and Virginia.",
    "kind": "category"
  },
  {
    "path": "/blog",
    "url": "https://zoeeventsdmv.com/blog",
    "title": "Event Tips & Ideas | Zoe Events & Party Rental Blog",
    "h1": "Transform Your Outdoor Event with Professional Tent Installations",
    "headings": [
      "Transform Your Outdoor Event with Professional Tent Installations",
      "A Glamorous 60th Birthday Bash at the Hilton Baltimore BWI Airport",
      "Zoe Event Rentals",
      "Contact Us by Phone"
    ],
    "category": null,
    "topic": "blog",
    "intent": "informational",
    "location": "DMV",
    "excerpt": "Insights, tips, and event inspiration from Zoe Events and Party Rentals",
    "kind": "blog"
  },
  {
    "path": "/blog/60th-birthday-hilton-baltimore-event-setup",
    "url": "https://zoeeventsdmv.com/blog/60th-birthday-hilton-baltimore-event-setup",
    "title": "Elegant 60th Birthday Celebration | Luxury Event Rentals & Decor",
    "h1": "A Glamorous 60th Birthday Bash at the Hilton Baltimore BWI Airport",
    "headings": [
      "A Glamorous 60th Birthday Bash at the Hilton Baltimore BWI Airport",
      "Setting the Scene: Luxury Meets Personal Touch",
      "Behind the Scenes: In-Depth, Hands-On Coordination",
      "Behind the Scenes: Crafting the Perfect Celebration",
      "The Guest Experience: Elegance, Celebration, and Comfort",
      "Statement Decor Pieces That Stole the Show",
      "Plan Your Next Milestone Celebration With Us"
    ],
    "category": null,
    "topic": "blog 60th birthday hilton baltimore event setup",
    "intent": "informational",
    "location": "DMV",
    "excerpt": "Case study of luxury 60th birthday at Hilton Baltimore BWI. Featured: Chiavari chairs, sequin backdrops, floral installations, marquee numbers, crystal chargers. Emphasizes hands-on coordination and curated decor.",
    "kind": "blog"
  },
  {
    "path": "/blog/tent-rental-installation-services",
    "url": "https://zoeeventsdmv.com/blog/tent-rental-installation-services",
    "title": "Tent Rental & Installation Services | Zoe Events DMV",
    "h1": "Transform Your Outdoor Event with Professional Tent Installations",
    "headings": [
      "Transform Your Outdoor Event with Professional Tent Installations",
      "Why Consider a Tent for Your Event?",
      "The Zoe Events DMV Tent Experience",
      "When you book with them, you can expect:",
      "Tent Styles to Suit Every Occasion",
      "What Makes Zoe Events DMV Stand Out",
      "The Team Behind the Tents",
      "Book Your Tent Installation Today",
      "Zoe Event Rentals",
      "Contact Us by Phone"
    ],
    "category": "tents",
    "topic": "blog tent rental installation services",
    "intent": "informational",
    "location": "DMV",
    "excerpt": "Professional tent rental and installation for outdoor events. Covers weather protection, customizable layouts, complete setup. Tent types: frame tents, canopy tents, high peak structures, large event setups. Integrated styling with lighting, furniture, decor.",
    "kind": "blog"
  },
  {
    "path": "/centerpieces",
    "url": "https://zoeeventsdmv.com/centerpieces",
    "title": "Decor Rentals | Zoe Events & Party Rental",
    "h1": null,
    "headings": [],
    "category": "decor",
    "topic": "centerpieces",
    "intent": "transactional",
    "location": "DMV",
    "excerpt": "Decor rental inventory from Zoe Events, serving DC, Maryland and Virginia.",
    "kind": "category"
  },
  {
    "path": "/children",
    "url": "https://zoeeventsdmv.com/children",
    "title": "Seating Rentals | Zoe Events & Party Rental",
    "h1": null,
    "headings": [],
    "category": "seating",
    "topic": "children",
    "intent": "transactional",
    "location": "DMV",
    "excerpt": "Seating rental inventory from Zoe Events, serving DC, Maryland and Virginia.",
    "kind": "category"
  },
  {
    "path": "/contact",
    "url": "https://zoeeventsdmv.com/contact",
    "title": "Contact Us | Zoe Events & Party Rental | (301) 291-5296",
    "h1": null,
    "headings": [
      "Visit us",
      "Hours",
      "Phone",
      "Email",
      "Zoe Event Rentals",
      "Contact Us by Phone"
    ],
    "category": null,
    "topic": "contact",
    "intent": "navigational",
    "location": "DMV",
    "excerpt": "- Address: \"12712 Rock Creek Mill Rd #4A, North Bethesda, MD 20852\" - Hours: Mon-Fri 10am-6pm; Sat 10am-1pm - Phone: (301) 291-5296 - Email: hello@zoeeventsdmv.com - Note: \"Showroom by appointment during normal office hours. Evening/weekend appointments available upon request.\"",
    "kind": "info"
  },
  {
    "path": "/corporate-events",
    "url": "https://zoeeventsdmv.com/corporate-events",
    "title": "Corporate Event Rentals | Zoe Events -- Washington DC, Maryland, Virginia",
    "h1": null,
    "headings": [
      "Event Rentals For Your D.C. Corporate Event",
      "Everything You Need for Your D.C. Corporate Event",
      "Why Choose Zoe Event Rentals?",
      "Unparalleled Quality",
      "Wide Selection",
      "Exceptional Service",
      "Competitive Pricing",
      "Exclusive B2B Benefits",
      "Custom Solutions",
      "Dedicated Account Manager",
      "Flexible Payment Options",
      "What's Like to Work with US",
      "Work with US",
      "Celebration In Style Starts Here"
    ],
    "category": "corporate",
    "topic": "corporate events",
    "intent": "commercial",
    "location": "DMV",
    "excerpt": "Premium corporate event equipment across DC/MD/VA. Services: seating, tables, tents, lighting, staging, AV equipment. Value propositions: unparalleled quality, wide selection, exceptional service, competitive pricing. B2B benefits: custom solutions, dedicated account manager, flexible payment.",
    "kind": "service"
  },
  {
    "path": "/crowd-control-equipment",
    "url": "https://zoeeventsdmv.com/crowd-control-equipment",
    "title": "Crowd Control Rentals | Zoe Events & Party Rental",
    "h1": null,
    "headings": [],
    "category": "crowd control",
    "topic": "crowd control equipment",
    "intent": "transactional",
    "location": "DMV",
    "excerpt": "Crowd Control rental inventory from Zoe Events, serving DC, Maryland and Virginia.",
    "kind": "category"
  },
  {
    "path": "/dancefloors",
    "url": "https://zoeeventsdmv.com/dancefloors",
    "title": "Dance Floors Rentals | Zoe Events & Party Rental",
    "h1": null,
    "headings": [],
    "category": "dance floors",
    "topic": "dancefloors",
    "intent": "transactional",
    "location": "DMV",
    "excerpt": "Dance Floors rental inventory from Zoe Events, serving DC, Maryland and Virginia.",
    "kind": "category"
  },
  {
    "path": "/dining-chairs",
    "url": "https://zoeeventsdmv.com/dining-chairs",
    "title": "Chairs Rentals | Zoe Events & Party Rental",
    "h1": null,
    "headings": [],
    "category": "chairs",
    "topic": "dining chairs",
    "intent": "transactional",
    "location": "DMV",
    "excerpt": "Chairs rental inventory from Zoe Events, serving DC, Maryland and Virginia.",
    "kind": "category"
  },
  {
    "path": "/event-extras-rentals",
    "url": "https://zoeeventsdmv.com/event-extras-rentals",
    "title": "Extras Rentals | Zoe Events & Party Rental",
    "h1": null,
    "headings": [],
    "category": "extras",
    "topic": "event extras rentals",
    "intent": "transactional",
    "location": "DMV",
    "excerpt": "Extras rental inventory from Zoe Events, serving DC, Maryland and Virginia.",
    "kind": "category"
  },
  {
    "path": "/faq",
    "url": "https://zoeeventsdmv.com/faq",
    "title": "FAQ | Plan Your Event Today",
    "h1": null,
    "headings": [
      "Zoe Event Rentals",
      "Tables | Chairs | Decor | Audio | Video Lighting | Bars | Marquee Light Up Alphabet Bounce Houses | Pipe and Drape | Dance Floor | Staging",
      "Contact Us by Phone (301) 291-5296"
    ],
    "category": null,
    "topic": "faq",
    "intent": "informational",
    "location": "DMV",
    "excerpt": "Find answers to common questions about event rental booking, delivery, payments, setup services, and more from Zoe Events and Party Rentals serving DC, Maryland, and Virginia.",
    "kind": "info"
  },
  {
    "path": "/flooring-equipment",
    "url": "https://zoeeventsdmv.com/flooring-equipment",
    "title": "Flooring Rentals | Zoe Events & Party Rental",
    "h1": null,
    "headings": [],
    "category": "flooring",
    "topic": "flooring equipment",
    "intent": "transactional",
    "location": "DMV",
    "excerpt": "Flooring rental inventory from Zoe Events, serving DC, Maryland and Virginia.",
    "kind": "category"
  },
  {
    "path": "/generator-and-power-equipment-rentals",
    "url": "https://zoeeventsdmv.com/generator-and-power-equipment-rentals",
    "title": "Power Rentals | Zoe Events & Party Rental",
    "h1": null,
    "headings": [],
    "category": "power",
    "topic": "generator and power equipment rentals",
    "intent": "transactional",
    "location": "DMV",
    "excerpt": "Power rental inventory from Zoe Events, serving DC, Maryland and Virginia.",
    "kind": "category"
  },
  {
    "path": "/heating-equipment-rentals",
    "url": "https://zoeeventsdmv.com/heating-equipment-rentals",
    "title": "Heating & Cooling Rentals | Zoe Events & Party Rental",
    "h1": null,
    "headings": [],
    "category": "heating & cooling",
    "topic": "heating equipment rentals",
    "intent": "transactional",
    "location": "DMV",
    "excerpt": "Heating & Cooling rental inventory from Zoe Events, serving DC, Maryland and Virginia.",
    "kind": "category"
  },
  {
    "path": "/inventory",
    "url": "https://zoeeventsdmv.com/inventory",
    "title": "Event Rental Inventory | Zoe Events & Party Rental -- DMV Area",
    "h1": "Transform Your Event Into a Cherished Memory",
    "headings": [
      "Transform Your Event Into a Cherished Memory",
      "Category headings: Arches, Centerpieces, Bar Stools, Tables, Children, Dining Chairs, Table Top, Signage, Tents & Canopies, Textiles, Dance Floors, Bars/Shelving/Pedestals, Seating, Sofas/Sectionals/Settees, Backdrops, Generators & Power Equipment, Staging, Heating & Cooling, Crowd Control, Pipe and Drapes, Flooring, Audio Equipment, Audio Visual Equipment, Event Extras"
    ],
    "category": null,
    "topic": "inventory",
    "intent": "transactional",
    "location": "DMV",
    "excerpt": null,
    "kind": "other"
  },
  {
    "path": "/our-offerings",
    "url": "https://zoeeventsdmv.com/our-offerings",
    "title": "Our Offerings",
    "h1": null,
    "headings": [],
    "category": null,
    "topic": "our offerings",
    "intent": "transactional",
    "location": "DMV",
    "excerpt": null,
    "kind": "other"
  },
  {
    "path": "/pipe-and-drapes-rentals",
    "url": "https://zoeeventsdmv.com/pipe-and-drapes-rentals",
    "title": "Pipe And Drape Rentals | Zoe Events & Party Rental",
    "h1": null,
    "headings": [],
    "category": "pipe and drape",
    "topic": "pipe and drapes rentals",
    "intent": "transactional",
    "location": "DMV",
    "excerpt": "Pipe And Drape rental inventory from Zoe Events, serving DC, Maryland and Virginia.",
    "kind": "category"
  },
  {
    "path": "/rental-search",
    "url": "https://zoeeventsdmv.com/rental-search",
    "title": "Rental Search",
    "h1": null,
    "headings": [],
    "category": null,
    "topic": "rental search",
    "intent": "transactional",
    "location": "DMV",
    "excerpt": null,
    "kind": "other"
  },
  {
    "path": "/seating",
    "url": "https://zoeeventsdmv.com/seating",
    "title": "Seating Rentals | Zoe Events & Party Rental",
    "h1": null,
    "headings": [],
    "category": "seating",
    "topic": "seating",
    "intent": "transactional",
    "location": "DMV",
    "excerpt": "Seating rental inventory from Zoe Events, serving DC, Maryland and Virginia.",
    "kind": "category"
  },
  {
    "path": "/signage",
    "url": "https://zoeeventsdmv.com/signage",
    "title": "Decor Rentals | Zoe Events & Party Rental",
    "h1": null,
    "headings": [],
    "category": "decor",
    "topic": "signage",
    "intent": "transactional",
    "location": "DMV",
    "excerpt": "Decor rental inventory from Zoe Events, serving DC, Maryland and Virginia.",
    "kind": "category"
  },
  {
    "path": "/social-events",
    "url": "https://zoeeventsdmv.com/social-events",
    "title": "Social & Private Event Rentals | Zoe Events -- DMV Area",
    "h1": "Event Rentals For Your D.C. Social Event",
    "headings": [
      "Event Rentals For Your D.C. Social Event",
      "Everything You Need for Your D.C. Social Event",
      "Why Choose Zoe Event Rentals?",
      "Unparalleled Quality",
      "Wide Selection",
      "Exceptional Service",
      "Competitive Pricing",
      "What's Like to Work with US",
      "Celebration In Style Starts Here",
      "Zoe Event Rentals",
      "Contact Us by Phone"
    ],
    "category": "social",
    "topic": "social events",
    "intent": "commercial",
    "location": "DMV",
    "excerpt": null,
    "kind": "service"
  },
  {
    "path": "/sofas",
    "url": "https://zoeeventsdmv.com/sofas",
    "title": "Lounge Rentals | Zoe Events & Party Rental",
    "h1": null,
    "headings": [],
    "category": "lounge",
    "topic": "sofas",
    "intent": "transactional",
    "location": "DMV",
    "excerpt": "Lounge rental inventory from Zoe Events, serving DC, Maryland and Virginia.",
    "kind": "category"
  },
  {
    "path": "/staging-rentals",
    "url": "https://zoeeventsdmv.com/staging-rentals",
    "title": "Staging Rentals | Zoe Events & Party Rental",
    "h1": null,
    "headings": [],
    "category": "staging",
    "topic": "staging rentals",
    "intent": "transactional",
    "location": "DMV",
    "excerpt": "Staging rental inventory from Zoe Events, serving DC, Maryland and Virginia.",
    "kind": "category"
  },
  {
    "path": "/table-top",
    "url": "https://zoeeventsdmv.com/table-top",
    "title": "Tableware Rentals | Zoe Events & Party Rental",
    "h1": null,
    "headings": [],
    "category": "tableware",
    "topic": "table top",
    "intent": "transactional",
    "location": "DMV",
    "excerpt": "Tableware rental inventory from Zoe Events, serving DC, Maryland and Virginia.",
    "kind": "category"
  },
  {
    "path": "/tables",
    "url": "https://zoeeventsdmv.com/tables",
    "title": "Tables Rentals | Zoe Events & Party Rental",
    "h1": null,
    "headings": [],
    "category": "tables",
    "topic": "tables",
    "intent": "transactional",
    "location": "DMV",
    "excerpt": "Tables rental inventory from Zoe Events, serving DC, Maryland and Virginia.",
    "kind": "category"
  },
  {
    "path": "/tents",
    "url": "https://zoeeventsdmv.com/tents",
    "title": "Tents Rentals | Zoe Events & Party Rental",
    "h1": null,
    "headings": [],
    "category": "tents",
    "topic": "tents",
    "intent": "transactional",
    "location": "DMV",
    "excerpt": "Tents rental inventory from Zoe Events, serving DC, Maryland and Virginia.",
    "kind": "category"
  },
  {
    "path": "/textiles",
    "url": "https://zoeeventsdmv.com/textiles",
    "title": "Linens Rentals | Zoe Events & Party Rental",
    "h1": null,
    "headings": [],
    "category": "linens",
    "topic": "textiles",
    "intent": "transactional",
    "location": "DMV",
    "excerpt": "Linens rental inventory from Zoe Events, serving DC, Maryland and Virginia.",
    "kind": "category"
  },
  {
    "path": "/weddings",
    "url": "https://zoeeventsdmv.com/weddings",
    "title": "Wedding Rentals | Zoe Events & Party Rental -- DC, MD & VA",
    "h1": "Event Rentals For Your D.C. Wedding",
    "headings": [
      "Event Rentals For Your D.C. Wedding",
      "wedding seating, tables, lighting & more.",
      "Everything You Need for Your D.C. Wedding",
      "Why Choose Zoe Event Rentals?",
      "Unparalleled Quality",
      "Wide Selection",
      "Exceptional Service",
      "Competitive Pricing",
      "What's Like to Work with US",
      "Celebration In Style Starts Here",
      "Zoe Event Rentals"
    ],
    "category": "weddings",
    "topic": "weddings",
    "intent": "commercial",
    "location": "DMV",
    "excerpt": "Tables, chairs, tents, lighting, dance floors, staging, decor, audio/video equipment, bars, marquee letters, bounce houses, pipe and drape for DC-area weddings.",
    "kind": "service"
  }
];
